name: Deploy NCC-ERP-AMS-FE to server using Docker

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ams-dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install package
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          REACT_APP_API_PROXY: ${{secrets.REACT_APP_API_PROXY}}
          REACT_APP_AUTH_CLIENT_ID: ${{secrets.REACT_APP_AUTH_CLIENT_ID}}
          REACT_APP_AUTH_SECRET_KEY: ${{secrets.REACT_APP_AUTH_SECRET_KEY}}
          REACT_APP_SHOW_MANUAL_LOGIN: ${{secrets.REACT_APP_SHOW_MANUAL_LOGIN}}
          CI: ""

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Remove old image
        run: docker rmi ncc-erp-ams-fe:latest || true

      - name: Build Docker image
        run: docker build -t ncc-erp-ams-fe:latest .

  deploy:
    runs-on: ams-dev
    needs:
      - build

    steps:
      - name: Check Docker installation
        run: |
          if ! command -v docker &> /dev/null
          then
            echo "Docker could not be found. Please install Docker."
            exit 1
          else
            echo "Docker is already installed."
          fi

      - name: Stop and remove old container
        run: |
          docker compose -f /home/nccsoft/ams-dev-docker/docker-compose.dev.yml down

      - name: Run Docker Compose
        run: |
          docker compose -f /home/nccsoft/ams-dev-docker/docker-compose.dev.yml up -d
